# Flutter build
variables:
  projectDirectory: '.'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'custom'
        customVersion: '2.8.0'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
        buildFlavour: dev
        entryPoint: lib/main_dev.dart

  
    # - task: AndroidSigning@3
    #   displayName: 'Signing and aligning APK file(s) **/*.apk'
    #   inputs:
    #     apkFiles: '**/*.apk'
    #     apksign: true
    #     apksignerKeystoreFile: key.jks
    #     apksignerKeystorePassword: $(keypassword)
    #     apksignerKeystoreAlias: $(key)
    #     apksignerKeyPassword: $(keypassword)
    # - task: CopyFiles@2
    #   inputs:
    #     contents: '**/*.apk'
    #     targetFolder: '$(build.artifactStagingDirectory)'
    # - task: PublishBuildArtifacts@1
